### ISSUE TITLE
为何ssd安卓版，安装不成功？

### ISSUE THREAD

**Issue by LewisYeung001** [CGDF-Github/SSD-Android#1]
安装后，显示程序未安装。

手机无360，百度等
是不是要root？

**Comment by CGDF-Github** [comment]
@LewisYeung001 你为什么不先看一下release里的说明呢？

**Comment by ue406** [comment]
机型Smartisan M1L，提示为未安装应用程序。

**Comment by CGDF-Github** [comment]
> 机型Smartisan M1L，提示为未安装应用程序。

请问，如果安装ssr/ssrr是否可以正常安装？

**Comment by ue406** [comment]
0.0.0，ssr，ssrr都可以成功安装。

**Comment by CGDF-Github** [comment]
呃，安装0.0.1之前，0.0.0卸载了吗

**Comment by ue406** [comment]
打开了...啊。

**Comment by ue406** [comment]
安卓手机我玩了五六年了，而且在国内，打开这个东西算是常识吧。

**Comment by CGDF-Github** [comment]
@ue406 那只剩下一个推测，我给apk签名的时候用的是v2模式，可能不支持版本过低的Android，等我白天找几个朋友手机试试

**Comment by CGDF-Github** [comment]
@ue406 问题已确认，是因为只使用了v2签名，导致了5.0-6.0的手机无法安装SSD，我会尽快修复

**Comment by ue406** [comment]
谢谢。

**Comment by CGDF-Github** [comment]
> 谢谢。
[mobile-universal-release.zip](https://github.com/CGDF-Github/SSD-Android/files/2477187/mobile-universal-release.zip)

请尝试一下这个apk

**Comment by 110010110** [comment]
> > 谢谢。
> > [mobile-universal-release.zip](https://github.com/CGDF-Github/SSD-Android/files/2477187/mobile-universal-release.zip)
> 
> 请尝试一下这个apk

这个可以装。（换了个号）
