### ISSUE TITLE
自行编译出现了一丢丢问题

### ISSUE THREAD

**Issue by kaniwow** [CGDF-Github/SSD-Android#22]
我在win上gitclone了下您的代码想自行编译，但是初始化环境有个这样的提示，请问有解决方案吗

> Server does not allow request for unadvertised object d58aa8b97d7871a6d5d77dbeb0b721eb2980175d
Fetched in submodule path 'core/src/main/jni/badvpn', but it did not contain d58aa8b97d7871a6d5d77dbeb0b721eb2980175d. Direct fetching of that commit failed.

**Comment by CGDF-Github** [comment]
已修复，感谢反馈
