### ISSUE TITLE
gradle版本限制太严重了，顺便提几个建议

### ISSUE THREAD

**Issue by kaniwow** [CGDF-Github/SSD-Android#24]
我今天重新编译了一下APP，代码0 errors，最后弹了一个gradle版本太高以至于无法加载模块

然后studio还爆了Warning，意思是有两个API即将更换，建议换方法，我给你粘贴一下。毕竟API等级越高，google给予的限制越多，我个人觉得还是更新下方法比较好

`WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompile(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
Affected Modules: plugin`

`WARNING: API 'variant.getExternalNativeBuildTasks()' is obsolete and has been replaced with 'variant.getExternalNativeBuildProviders()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getExternalNativeBuildTasks(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
Affected Modules: mobile`

**Comment by kaniwow** [comment]
哦对了，好几次了都Android Studio都爆了

> ERROR: [TAG] Failed to resolve variable '${project.version}'

果然还是还是要命令行编译大法保命么，枯了

**Comment by xuhaoyang** [comment]
@kaniwow 用新as不就行了

**Comment by CGDF-Github** [comment]
gradle这些，是上游的事情
