### ISSUE TITLE
希望接下来不要一棍子打死所有小米设备

### ISSUE THREAD

**Issue by OharaRinne** [CGDF-Github/SSD-Android#25]
我从来不用MIUI，因为小米便宜买的小米，然后刷的Google PixelExperience...

**Comment by CGDF-Github** [comment]
嗯？你的设备运行SSD的时候上会弹出MIUI警告吗？

**Comment by OharaRinne** [comment]
会弹出 SSD 未来将无法运行于 xiaomi 设备

**Comment by OharaRinne** [comment]
就是toast提示

**Comment by CGDF-Github** [comment]
[app-debug.zip](https://github.com/CGDF-Github/SSD-Android/files/2962484/app-debug.zip)
这倒不是我的本意， 如果可以，请安装运行一下这个app，然后截图给我看一下（然后这个app就可以卸载了）

**Comment by OharaRinne** [comment]
![Screenshot_20190314-004344](https://user-images.githubusercontent.com/45261195/54297780-75aa2d80-45f2-11e9-8c8e-f7932a428922.png)
这样的

**Comment by CGDF-Github** [comment]
[app-debug.zip](https://github.com/CGDF-Github/SSD-Android/files/2963090/app-debug.zip)
可以再安装运行一下这个，然后截图一下吗？我觉得这次应该可以了

**Comment by OharaRinne** [comment]
显示  Xiaomi,Xiaomi.

**Comment by CGDF-Github** [comment]
那还蛮尴尬的，这次取的是rom的数据，这特么不和MIUI没区别么。。。

**Comment by CGDF-Github** [comment]
你有root吗？如果root了的话可以把/system/build.prop文件发上来看一下吗？没root的话我再想想办法

**Comment by OharaRinne** [comment]
或许可以检测小米设备是否为MIUI？
https://blog.csdn.net/qq_34858228/article/details/54836230

**Comment by OharaRinne** [comment]
有root，稍等

**Comment by OharaRinne** [comment]
[build.zip](https://github.com/CGDF-Github/SSD-Android/files/2963212/build.zip)

**Comment by OharaRinne** [comment]
https://blog.csdn.net/lovelyelfpop/article/details/65440420
或许可以试试用这种方法检测是否为指定ROM？

**Comment by CGDF-Github** [comment]
> https://blog.csdn.net/lovelyelfpop/article/details/65440420
> 或许可以试试用这种方法检测是否为指定ROM？

这个方法倒是知道，但是发现不适用于米1。嘛算了，米1也没人用了吧，也没其他更好的办法了

**Comment by CGDF-Github** [comment]
[mobile-universal-debug.zip](https://github.com/CGDF-Github/SSD-Android/files/2963424/mobile-universal-debug.zip)
这次应该可以了， 如果有兴趣可以试一下，这个是debug版的，安装之前可以需要卸载release版

**Comment by OharaRinne** [comment]
ok,nice
辛苦作者sama啦

**Comment by summershrimp** [comment]
能问下为何不允许在 某些设备上运行么
