### ISSUE TITLE
使用中的订阅配置删除后测速闪退

### ISSUE THREAD

**Issue by redaiert2** [CGDF-Github/SSD-Android#26]
如标题所言。
在使用中的订阅配置并没有强制保护不允许用户滑动删除。如果将使用中的订阅配置删除后，这时连接依旧存在并可用，此时若点击测试连接软件便会闪退（但后台连接依旧存在，并在再次打开软件后依旧存在，之前的闪退bug也可以再次复现）。
希望作者可以解决下。

**Comment by CGDF-Github** [comment]
recorded

**Comment by CGDF-Github** [comment]
fixed
