### ISSUE TITLE
订阅出现闪退

### ISSUE THREAD

**Issue by huanglittleming** [CGDF-Github/SSD-Android#3]
安卓版本6.0.1
Flyme6100A
在尝试添加订阅时出现闪退，使用版本是issues中出现的对安卓5 6安装的修复版

**Comment by huanglittleming** [comment]
https://raw.githubusercontent.com/ImLaoD/sub/master/ssrshare.com
这是公开的订阅地址，ssr原版客户端可订阅，SSD客户端闪退

**Comment by huanglittleming** [comment]
https://raw.githubusercontent.com/ImLaoD/sub/master/ssrshare.com
这是公开的订阅地址，ssr原版客户端可订阅，SSD客户端闪退

**Comment by CGDF-Github** [comment]
@huanglittleming SSD并不支持SSR/SSRR的订阅链接，不过闪退确实是个BUG，谢谢合作

**Comment by huanglittleming** [comment]
> @huanglittleming SSD并不支持SSR/SSRR的订阅链接，不过闪退确实是个BUG，谢谢合作

SSD支持哪种订阅链接，用原版SS吗？

**Comment by CGDF-Github** [comment]
@huanglittleming SSD支持SSD订阅链接。
SSD订阅是为机场而设计，通常只有机场会发布SSD订阅。
如果想自己生成订阅，请自学json并对照wiki手工生成。
