### ISSUE TITLE
能不能不要使用同一个包名，如此很不方便啊

### ISSUE THREAD

**Issue by mapleshadow** [CGDF-Github/SSD-Android#5]
RT，这样原版就不能装了

**Comment by CGDF-Github** [comment]
@mapleshadow 内测版中包名已修改，并正处于内测中，请期待下一个版本

**Comment by CGDF-Github** [comment]
附：因本期内测内容略多，可能得等至少两个星期才会放出正式版

**Comment by xuhaoyang** [comment]
@CGDF-Github 能帮着一起开发么-。-，bug太多，我现在用起来也给予的现在改了东西，github上没有记录，都不知道改了什么

**Comment by CGDF-Github** [comment]
@xuhaoyang 好的
